import { MasterNutrientItemsModel } from "../master/nutrients/nutrient.model";

export const MASTER_NUTRIENT_MOCKS: MasterNutrientItemsModel[] = [
  {
    nutrientId: 'nut_001',
    nutrientCode: 'PROCNT',
    nameThai: 'โปรตีน',
    nameEng: 'Protein',
    defaultUnit: 'g',
    nutrientGroupId: 'grp_macro',
    groupName: 'สารอาหารหลัก',
    displayOrder: 2,
    status: 'ACTIVE',
    updatedAt: '2025-11-01T10:00:00Z',
    updatedBy: 'admin',
  },
  {
    nutrientId: 'nut_002',
    nutrientCode: 'FAT',
    nameThai: 'ไขมันทั้งหมด',
    nameEng: 'Total Fat',
    defaultUnit: 'g',
    nutrientGroupId: 'grp_macro',
    groupName: 'สารอาหารหลัก',
    displayOrder: 4,
    status: 'ACTIVE',
    updatedAt: '2025-11-01T11:00:00Z',
    updatedBy: 'admin',
  },
  {
    nutrientId: 'nut_003',
    nutrientCode: 'CHOCDF',
    nameThai: 'คาร์โบไฮเดรต',
    nameEng: 'Carbohydrate',
    defaultUnit: 'g',
    nutrientGroupId: 'grp_macro',
    groupName: 'สารอาหารหลัก',
    displayOrder: 3,
    status: 'ACTIVE',
    updatedAt: '2025-11-01T12:00:00Z',
    updatedBy: 'admin',
  },
  {
    nutrientId: 'nut_004',
    nutrientCode: 'VITC',
    nameThai: 'วิตามินซี',
    nameEng: 'Vitamin C',
    defaultUnit: 'mg',
    nutrientGroupId: 'grp_vitamin',
    groupName: 'วิตามิน',
    displayOrder: 21,
    status: 'ACTIVE',
    updatedAt: '2023-10-30T09:00:00Z',
    updatedBy: 'user01',
  },
  {
    nutrientId: 'nut_005',
    nutrientCode: 'NA',
    nameThai: 'โซเดียม',
    nameEng: 'Sodium',
    defaultUnit: 'mg',
    nutrientGroupId: 'grp_mineral',
    groupName: 'แร่ธาตุ',
    displayOrder: 35,
    status: 'INACTIVE',
    updatedAt: '2023-10-28T15:00:00Z',
    updatedBy: 'admin',
  },
];