import { MasterNutrientCategoriesItemsModel } from "../master/nutrient-categories/nutrient-categories.model";

// ข้อมูลจำลอง
export const MASTER_NUTRIENT_CATEGORIES_MOCKS: MasterNutrientCategoriesItemsModel[] = [
//  {
//     objectId: 'raw_001',
//     materialId: 'RM-0001',
//     nameThai: 'อกไก่ (ไม่ติดหนัง)',
//     nameEng: 'Chicken Breast (Skinless)',
//     categoryName: 'เนื้อสัตว์',
//     baseUnit: 'g',
//     baseQuantity: 100,
//     energyKcal: 165,
//     proteinG: 31,
//     carbohydrateG: 0,
//     fatTotalG: 3.6,
//     status: 'ACTIVE',
//     updatedAt: '2023-10-27T10:00:00Z',
//     updatedBy: 'admin',
//   },
//   {
//     objectId: 'raw_002',
//     materialId: 'RM-0002',
//     nameThai: 'ข้าวกล้องหอมมะลิ',
//     nameEng: 'Brown Jasmine Rice',
//     categoryName: 'ธัญพืช',
//     baseUnit: 'g',
//     baseQuantity: 100,
//     energyKcal: 111,
//     proteinG: 2.6,
//     carbohydrateG: 23,
//     fatTotalG: 0.9,
//     status: 'ACTIVE',
//     updatedAt: '2023-10-26T14:30:00Z',
//     updatedBy: 'admin',
//   },
//   {
//     objectId: 'raw_003',
//     materialId: 'RM-0003',
//     nameThai: 'บรอกโคลี',
//     nameEng: 'Broccoli',
//     categoryName: 'ผัก',
//     baseUnit: 'g',
//     baseQuantity: 100,
//     energyKcal: 34,
//     proteinG: 2.8,
//     carbohydrateG: 6.6,
//     fatTotalG: 0.4,
//     status: 'ACTIVE',
//     updatedAt: '2023-10-25T09:00:00Z',
//     updatedBy: 'user01',
//   },
//   {
//     objectId: 'raw_004',
//     materialId: 'RM-0004',
//     nameThai: 'น้ำมันมะกอก',
//     nameEng: 'Olive Oil',
//     categoryName: 'ไขมันและน้ำมัน',
//     baseUnit: 'ml',
//     baseQuantity: 100,
//     energyKcal: 884,
//     proteinG: 0,
//     carbohydrateG: 0,
//     fatTotalG: 100,
//     status: 'INACTIVE',
//     updatedAt: '2023-10-20T11:00:00Z',
//     updatedBy: 'admin',
//   },
//   {
//     objectId: 'raw_005',
//     materialId: 'RM-0005',
//     nameThai: 'ไข่ไก่ (เบอร์ 2)',
//     nameEng: 'Egg (Large)',
//     categoryName: 'ไข่และผลิตภัณฑ์',
//     baseUnit: 'g',
//     baseQuantity: 50, // ไข่ 1 ฟองหนักประมาณ 50g
//     energyKcal: 72,
//     proteinG: 6,
//     carbohydrateG: 0.4,
//     fatTotalG: 5,
//     status: 'ACTIVE',
//     updatedAt: '2023-10-28T08:20:00Z',
//     updatedBy: 'admin',
//   },
  // เพิ่มข้อมูลจำลองอื่นๆ ได้ตามต้องการ
];